# Generated by Django 4.1.1 on 2022-11-30 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainBorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='applicationinstance',
            old_name='application',
            new_name='instance_of',
        ),
        migrations.AlterField(
            model_name='connection',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider_set', to='api.pacport'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='requirer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requirer_set', to='api.pacport'),
        ),
    ]
