# Generated by Django 4.1.1 on 2022-12-01 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_domainborder_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connection',
            old_name='provider',
            new_name='provider_port',
        ),
        migrations.RenameField(
            model_name='connection',
            old_name='requirer',
            new_name='requirer_port',
        ),
        migrations.RemoveField(
            model_name='application',
            name='cpu',
        ),
        migrations.RemoveField(
            model_name='application',
            name='partition',
        ),
        migrations.AddField(
            model_name='applicationinstance',
            name='affinity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='applicationinstance',
            name='cpu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.cpu'),
        ),
        migrations.AddField(
            model_name='applicationinstance',
            name='instance_of_application',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='applicationinstance',
            name='partition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.partition'),
        ),
        migrations.AddField(
            model_name='applicationinstance',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_project_set', to='api.project'),
        ),
        migrations.AddField(
            model_name='applicationinstance',
            name='rampool',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='connection',
            name='identity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='domainborder',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.project'),
        ),
        migrations.AddField(
            model_name='pacport',
            name='provider',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='thread',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.project'),
        ),
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.project'),
        ),
        migrations.AlterField(
            model_name='applicationinstance',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
