# Generated by Django 4.1.1 on 2022-12-01 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_applicationinstance_node'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationinstance',
            name='cpu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_instance_set', to='api.cpu'),
        ),
        migrations.AlterField(
            model_name='applicationinstance',
            name='partition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_instance_set', to='api.partition'),
        ),
        migrations.AlterField(
            model_name='applicationinstance',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.project'),
        ),
    ]
