# Generated by Django 4.1.1 on 2022-12-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_applicationinstance_cpu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacport',
            name='DomainBorderConfig',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
