# Generated by Django 4.1.1 on 2022-12-05 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_applicationinstance_cpu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacport',
            name='domain_border',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.domainborder'),
        ),
    ]
