# Generated by Django 4.1.1 on 2022-12-06 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_provider_owner_connection_provider_app_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.project'),
        ),
    ]
