# Generated by Django 4.1.1 on 2022-12-06 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_pacport_domainborderconfig'),
        ('api', '0011_connection_project'),
    ]

    operations = [
    ]
