# Generated by Django 4.1.2 on 2022-12-06 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_merge_20221206_1024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pacport',
            old_name='DomainBorderConfig',
            new_name='DomainBorderConfiguration',
        ),
    ]
