# Generated by Django 4.1.1 on 2022-12-07 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_merge_20221206_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='provider_app',
        ),
        migrations.RemoveField(
            model_name='connection',
            name='requirer_app',
        ),
    ]
