# Generated by Django 4.1.1 on 2022-09-29 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Partition',
            fields=[
                ('id', models.BigAutoField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=20)),
                ('node', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.node')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PartitionFailure',
            fields=[
                ('id', models.BigAutoField(default=0, primary_key=True, serialize=False)),
                ('failure_mode_effect', models.TextField(default='', max_length=100)),
                ('subsystem_effect', models.TextField(default='', max_length=100)),
                ('aircraft_level_effect', models.TextField(default='', max_length=100)),
                ('event', models.CharField(default='', max_length=50)),
                ('mission', models.CharField(default='', max_length=50)),
                ('category', models.CharField(default='', max_length=50)),
                ('criticality', models.CharField(default='', max_length=50)),
                ('comments', models.TextField(default='', max_length=500)),
                ('partition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.partition')),
            ],
        ),
        migrations.CreateModel(
            name='NodeFailure',
            fields=[
                ('id', models.BigAutoField(default=0, primary_key=True, serialize=False)),
                ('event', models.CharField(max_length=200)),
                ('flight_phase', models.CharField(max_length=50)),
                ('comments', models.TextField(default='', max_length=500)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.node')),
            ],
        ),
        migrations.AddField(
            model_name='node',
            name='project',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.project'),
        ),
        migrations.CreateModel(
            name='MaterialGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materal_group', models.CharField(max_length=50)),
                ('application', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.application')),
                ('partition', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.partition')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='partition_failure',
            field=models.ManyToManyField(default='', to='api.partitionfailure'),
        ),
    ]
