# Generated by Django 4.1.1 on 2022-09-23 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subsystem',
            fields=[
                ('material_group', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('effect', models.TextField(max_length=200)),
                ('comment', models.TextField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='id',
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Partition',
            fields=[
                ('partition_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('application_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('failure_mode_effect', models.CharField(max_length=50)),
                ('flight_phase', models.CharField(max_length=50)),
                ('aircraft_level_effect', models.TextField(max_length=500)),
                ('mission', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('partition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.partition')),
            ],
        ),
    ]
