# Generated by Django 4.1.1 on 2022-09-26 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_project_subsystem_remove_person_id_alter_person_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('node_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='NodeFailure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.TextField(max_length=200)),
                ('flight_phase', models.CharField(max_length=50)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.node')),
            ],
        ),
        migrations.CreateModel(
            name='PartitionFailure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='Subsystem',
        ),
        migrations.RemoveField(
            model_name='application',
            name='aircraft_level_effect',
        ),
        migrations.RemoveField(
            model_name='application',
            name='category',
        ),
        migrations.RemoveField(
            model_name='application',
            name='failure_mode_effect',
        ),
        migrations.RemoveField(
            model_name='application',
            name='flight_phase',
        ),
        migrations.RemoveField(
            model_name='application',
            name='mission',
        ),
        migrations.RemoveField(
            model_name='application',
            name='partition',
        ),
        migrations.RemoveField(
            model_name='partition',
            name='project',
        ),
        migrations.AlterField(
            model_name='application',
            name='application_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='partition',
            name='partition_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='partitionfailure',
            name='partition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.partition'),
        ),
        migrations.AddField(
            model_name='application',
            name='partition_failure',
            field=models.ManyToManyField(to='api.partitionfailure'),
        ),
        migrations.AddField(
            model_name='partition',
            name='node',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.node'),
        ),
    ]
