# Generated by Django 4.1.1 on 2022-10-03 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_node_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodefailure',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node', to='api.node'),
        ),
    ]
