# Generated by Django 4.1.1 on 2022-10-03 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_nodefailure_node'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodefailure',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.node'),
        ),
    ]
