# Generated by Django 4.1.1 on 2022-12-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_provider_connection_provider_port_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='automated_test_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
