# Generated by Django 4.1.1 on 2022-10-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_nodefailure_node'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partition',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
