# Generated by Django 4.1.1 on 2022-09-29 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_application_material_group_nodefailure_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='project',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.project'),
        ),
    ]
