# Generated by Django 4.1.1 on 2022-09-29 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_node_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('belongs_to', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.person')),
            ],
        ),
    ]
