# Generated by Django 4.1.1 on 2022-10-13 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_partition_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NodeFC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redundant', models.CharField(default='false', max_length=20)),
                ('sync_loss', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NodeMC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='nodefailure',
            name='node',
        ),
        migrations.RemoveField(
            model_name='partitionfailure',
            name='partition',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_id',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='partition_failure',
        ),
        migrations.AddField(
            model_name='application',
            name='node',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.node'),
        ),
        migrations.AddField(
            model_name='node',
            name='load_set_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='node',
            name='platform',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='partition',
            name='fixed_start',
            field=models.BigIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='partition',
            name='is_ltm',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='partition',
            name='partition_id',
            field=models.IntegerField(default=None),
        ),
        migrations.DeleteModel(
            name='MaterialGroup',
        ),
        migrations.DeleteModel(
            name='NodeFailure',
        ),
        migrations.DeleteModel(
            name='PartitionFailure',
        ),
        migrations.AddField(
            model_name='nodemc',
            name='node',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.node'),
        ),
        migrations.AddField(
            model_name='nodefc',
            name='node',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.node'),
        ),
        migrations.AddField(
            model_name='cpu',
            name='node',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.node'),
        ),
        migrations.AddField(
            model_name='application',
            name='cpu',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.cpu'),
        ),
        migrations.AddField(
            model_name='partition',
            name='cpu',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.cpu'),
        ),
        migrations.AlterField(
            model_name='partition',
            name='node',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.nodefc'),
        ),
    ]
