# Generated by Django 4.1.1 on 2022-11-01 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_cpu_nodefc_nodemc_remove_nodefailure_node_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='nodemc',
            name='node',
        ),
        migrations.RemoveField(
            model_name='application',
            name='node',
        ),
        migrations.RemoveField(
            model_name='partition',
            name='node',
        ),
        migrations.AddField(
            model_name='cpu',
            name='accs_sync_master',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='cpu',
            name='domain_border',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='cpu',
            name='iop_ref',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='cpu',
            name='name',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='cpu',
            name='unit_id',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='node',
            name='redundant',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='node',
            name='sync_loss',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='application',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='node',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.node'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='type',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.DeleteModel(
            name='NodeFC',
        ),
        migrations.DeleteModel(
            name='NodeMC',
        ),
        migrations.AddField(
            model_name='connection',
            name='provider',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='connection_provider_set', to='api.application'),
        ),
        migrations.AddField(
            model_name='connection',
            name='requirer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='connection_requirer_set', to='api.application'),
        ),
    ]
