# Generated by Django 4.1.1 on 2022-11-02 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_connection_remove_nodemc_node_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='load_set_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='node',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='node',
            name='platform',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='node',
            name='project',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.project'),
        ),
        migrations.AlterField(
            model_name='node',
            name='redundant',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='node',
            name='sync_loss',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
