# Generated by Django 4.1.1 on 2022-12-05 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_pacport_domain_border'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacport',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.project'),
        ),
    ]
