# Generated by Django 4.1.1 on 2022-11-02 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_node_load_set_type_alter_node_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='cpu',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.cpu'),
        ),
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='connection',
            name='provider',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='connection_provider_set', to='api.application'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='requirer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='connection_requirer_set', to='api.application'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='accs_sync_master',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='domain_border',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='iop_ref',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='name',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='node',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.node'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='unit_id',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='partition',
            name='cpu',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.cpu'),
        ),
        migrations.AlterField(
            model_name='partition',
            name='is_ltm',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='partition',
            name='name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
