# Generated by Django 4.1.1 on 2022-12-06 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_connection_provider_owner_connection_provider_thread_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connection',
            old_name='provider_owner',
            new_name='provider_app',
        ),
        migrations.RemoveField(
            model_name='connection',
            name='provider_thread',
        ),
        migrations.RemoveField(
            model_name='connection',
            name='requirer_thread',
        ),
    ]
