# Generated by Django 4.1.2 on 2022-11-07 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_node_sync_loss'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='partition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.partition'),
        ),
    ]
