# Generated by Django 4.1.1 on 2022-11-18 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_application_partition'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentsDict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='KeyVal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('comment', models.TextField()),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.commentsdict')),
            ],
        ),
    ]
