# Generated by Django 4.1.2 on 2022-12-06 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_merge_20221206_1030'),
        ('api', '0013_rename_domainborderconfig_pacport_domainborderconfiguration'),
    ]

    operations = [
    ]
