# Generated by Django 4.1.1 on 2022-11-21 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_commentsdict_keyval'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyval',
            old_name='name',
            new_name='key',
        ),
    ]
