# Generated by Django 4.1.1 on 2022-11-23 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_name_keyval_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_project_set', to='api.project'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
